import React from 'react'
import {Container, Row, Col} from 'react-bootstrap'

const About = () =>{
    return (
        <>
        <Container style={{marginTop:'50px'}}>
            <h1>Who We Are </h1>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore saepe error accusamus aperiam culpa iste, esse corporis molestias possimus dolorum et, modi laudantium eveniet nostrum? Numquam sunt reiciendis libero, blanditiis nemo, maxime eum similique, magni inventore id repudiandae distinctio voluptatem dicta nobis nam ad culpa praesentium. Sunt officiis eos nihil tempora praesentium reiciendis facilis cupiditate unde, hic nobis doloremque, cum at quibusdam tempore. Sunt saepe, harum, possimus ullam id iste cupiditate beatae corporis, assumenda voluptatibus veritatis tempora. Quis vero, iure perspiciatis, mollitia consectetur aliquam, architecto praesentium hic dolorem similique rem. Nam quisquam, consequatur asperiores consequuntur quasi sequi autem id sed neque, tempore non provident adipisci consectetur eos exercitationem ducimus iusto. Quia voluptas soluta laboriosam in, ab autem, perferendis, culpa adipisci quam repellendus omnis odio cupiditate sint consequatur vitae pariatur delectus qui officia a. Repudiandae ducimus suscipit necessitatibus dolorem rem quo nemo autem aperiam vitae! Quae nostrum provident enim alias, deleniti quasi perferendis. Vitae autem repudiandae architecto delectus nostrum rerum hic consequuntur eius obcaecati, illum itaque perspiciatis magni placeat quam voluptate culpa quia eaque in! Voluptatum atque ad quidem aliquid, quaerat voluptas, accusamus, commodi ipsa maiores ut deserunt ex eius. Et numquam officia adipisci atque ratione illum ipsam quis nihil ut?</p>
            <h1> Our Speciality</h1>
            <Row>
                <Col md={6}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et soluta est provident aliquid ratione. Corporis non est tenetur corrupti minus deserunt fugit deleniti repellendus beatae veniam nihil nam, ratione hic natus facere quisquam sed veritatis dolorum modi iure incidunt, repellat nemo? Quod quaerat est quisquam numquam reprehenderit? Facere rem accusamus repudiandae dolorem aut. Eveniet iusto error animi odio aperiam quaerat, officia alias sit voluptatum aspernatur illum dolor esse quidem tempore adipisci reprehenderit ipsam maxime placeat ratione at. Aperiam assumenda quas eos adipisci doloribus, repellendus quos. Officiis, sit. Veniam, molestias temporibus! Ullam ad doloremque praesentium harum temporibus dolorum tenetur asperiores, aliquam pariatur modi fuga itaque porro eaque! Non temporibus deserunt facilis reiciendis praesentium! Earum facilis aspernatur temporibus nihil totam ratione eos enim magnam ex, nostrum facere quam cupiditate eum non eveniet ea magni possimus, accusamus libero impedit. Porro quidem esse dolorem maiores ut similique itaque, odio, veniam eligendi in eaque praesentium, repellendus ipsum illum animi beatae sit. Deserunt officiis consequatur et voluptates sint, eveniet error in repudiandae sit numquam? Officiis voluptatibus cum qui dolores perspiciatis beatae nulla maiores dicta. Quaerat dignissimos quibusdam facere laborum ipsa doloremque quos, officia dolor magnam numquam error minima at nobis possimus provident non atque natus eaque!</p>
                </Col>
                
                <Col md={6}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et soluta est provident aliquid ratione. Corporis non est tenetur corrupti minus deserunt fugit deleniti repellendus beatae veniam nihil nam, ratione hic natus facere quisquam sed veritatis dolorum modi iure incidunt, repellat nemo? Quod quaerat est quisquam numquam reprehenderit? Facere rem accusamus repudiandae dolorem aut. Eveniet iusto error animi odio aperiam quaerat, officia alias sit voluptatum aspernatur illum dolor esse quidem tempore adipisci reprehenderit ipsam maxime placeat ratione at. Aperiam assumenda quas eos adipisci doloribus, repellendus quos. Officiis, sit. Veniam, molestias temporibus! Ullam ad doloremque praesentium harum temporibus dolorum tenetur asperiores, aliquam pariatur modi fuga itaque porro eaque! Non temporibus deserunt facilis reiciendis praesentium! Earum facilis aspernatur temporibus nihil totam ratione eos enim magnam ex, nostrum facere quam cupiditate eum non eveniet ea magni possimus, accusamus libero impedit. Porro quidem esse dolorem maiores ut similique itaque, odio, veniam eligendi in eaque praesentium, repellendus ipsum illum animi beatae sit. Deserunt officiis consequatur et voluptates sint, eveniet error in repudiandae sit numquam? Officiis voluptatibus cum qui dolores perspiciatis beatae nulla maiores dicta. Quaerat dignissimos quibusdam facere laborum ipsa doloremque quos, officia dolor magnam numquam error minima at nobis possimus provident non atque natus eaque!</p>
                </Col>
            </Row>
            <Row>
                <h1> Our Chief</h1>
                <Col md={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et soluta est provident aliquid ratione. Corporis non est tenetur corrupti minus deserunt fugit deleniti repellendus beatae veniam nihil nam, ratione hic natus facere quisquam sed veritatis dolorum modi iure incidunt, repellat nemo? Quod quaerat est quisquam numquam reprehenderit? Facere rem accusamus repudiandae dolorem aut. Eveniet iusto error animi odio aperiam quaerat, officia alias sit voluptatum aspernatur illum dolor esse quidem tempore adipisci reprehenderit ipsam maxime placeat ratione at. Aperiam assumenda quas eos adipisci doloribus, repellendus quos. Officiis, sit. Veniam, molestias temporibus! Ullam ad doloremque praesentium harum temporibus dolorum tenetur asperiores, aliquam pariatur modi fuga itaque porro eaque! Non temporibus deserunt facilis reiciendis praesentium! Earum facilis aspernatur temporibus nihil totam ratione eos enim magnam ex, nostrum facere quam cupiditate eum non eveniet ea magni possimus, accusamus libero impedit. Porro quidem esse dolorem maiores ut similique itaque, odio, veniam eligendi in eaque praesentium, repellendus ipsum illum animi beatae sit. Deserunt officiis consequatur et voluptates sint, eveniet error in repudiandae sit numquam? Officiis voluptatibus cum qui dolores perspiciatis beatae nulla maiores dicta. Quaerat dignissimos quibusdam facere laborum ipsa doloremque quos, officia dolor magnam numquam error minima at nobis possimus provident non atque natus eaque!</p>
                    </Col>
                    <Col md={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et soluta est provident aliquid ratione. Corporis non est tenetur corrupti minus deserunt fugit deleniti repellendus beatae veniam nihil nam, ratione hic natus facere quisquam sed veritatis dolorum modi iure incidunt, repellat nemo? Quod quaerat est quisquam numquam reprehenderit? Facere rem accusamus repudiandae dolorem aut. Eveniet iusto error animi odio aperiam quaerat, officia alias sit voluptatum aspernatur illum dolor esse quidem tempore adipisci reprehenderit ipsam maxime placeat ratione at. Aperiam assumenda quas eos adipisci doloribus, repellendus quos. Officiis, sit. Veniam, molestias temporibus! Ullam ad doloremque praesentium harum temporibus dolorum tenetur asperiores, aliquam pariatur modi fuga itaque porro eaque! Non temporibus deserunt facilis reiciendis praesentium! Earum facilis aspernatur temporibus nihil totam ratione eos enim magnam ex, nostrum facere quam cupiditate eum non eveniet ea magni possimus, accusamus libero impedit. Porro quidem esse dolorem maiores ut similique itaque, odio, veniam eligendi in eaque praesentium, repellendus ipsum illum animi beatae sit. Deserunt officiis consequatur et voluptates sint, eveniet error in repudiandae sit numquam? Officiis voluptatibus cum qui dolores perspiciatis beatae nulla maiores dicta. Quaerat dignissimos quibusdam facere laborum ipsa doloremque quos, officia dolor magnam numquam error minima at nobis possimus provident non atque natus eaque!</p>
                    </Col>
                    <Col md={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et soluta est provident aliquid ratione. Corporis non est tenetur corrupti minus deserunt fugit deleniti repellendus beatae veniam nihil nam, ratione hic natus facere quisquam sed veritatis dolorum modi iure incidunt, repellat nemo? Quod quaerat est quisquam numquam reprehenderit? Facere rem accusamus repudiandae dolorem aut. Eveniet iusto error animi odio aperiam quaerat, officia alias sit voluptatum aspernatur illum dolor esse quidem tempore adipisci reprehenderit ipsam maxime placeat ratione at. Aperiam assumenda quas eos adipisci doloribus, repellendus quos. Officiis, sit. Veniam, molestias temporibus! Ullam ad doloremque praesentium harum temporibus dolorum tenetur asperiores, aliquam pariatur modi fuga itaque porro eaque! Non temporibus deserunt facilis reiciendis praesentium! Earum facilis aspernatur temporibus nihil totam ratione eos enim magnam ex, nostrum facere quam cupiditate eum non eveniet ea magni possimus, accusamus libero impedit. Porro quidem esse dolorem maiores ut similique itaque, odio, veniam eligendi in eaque praesentium, repellendus ipsum illum animi beatae sit. Deserunt officiis consequatur et voluptates sint, eveniet error in repudiandae sit numquam? Officiis voluptatibus cum qui dolores perspiciatis beatae nulla maiores dicta. Quaerat dignissimos quibusdam facere laborum ipsa doloremque quos, officia dolor magnam numquam error minima at nobis possimus provident non atque natus eaque!</p>
                    </Col>
                    <Col md={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et soluta est provident aliquid ratione. Corporis non est tenetur corrupti minus deserunt fugit deleniti repellendus beatae veniam nihil nam, ratione hic natus facere quisquam sed veritatis dolorum modi iure incidunt, repellat nemo? Quod quaerat est quisquam numquam reprehenderit? Facere rem accusamus repudiandae dolorem aut. Eveniet iusto error animi odio aperiam quaerat, officia alias sit voluptatum aspernatur illum dolor esse quidem tempore adipisci reprehenderit ipsam maxime placeat ratione at. Aperiam assumenda quas eos adipisci doloribus, repellendus quos. Officiis, sit. Veniam, molestias temporibus! Ullam ad doloremque praesentium harum temporibus dolorum tenetur asperiores, aliquam pariatur modi fuga itaque porro eaque! Non temporibus deserunt facilis reiciendis praesentium! Earum facilis aspernatur temporibus nihil totam ratione eos enim magnam ex, nostrum facere quam cupiditate eum non eveniet ea magni possimus, accusamus libero impedit. Porro quidem esse dolorem maiores ut similique itaque, odio, veniam eligendi in eaque praesentium, repellendus ipsum illum animi beatae sit. Deserunt officiis consequatur et voluptates sint, eveniet error in repudiandae sit numquam? Officiis voluptatibus cum qui dolores perspiciatis beatae nulla maiores dicta. Quaerat dignissimos quibusdam facere laborum ipsa doloremque quos, officia dolor magnam numquam error minima at nobis possimus provident non atque natus eaque!</p>
                    </Col>
            </Row>

        </Container>
        
        </>
    )
}

export default About
